apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
  namespace: champions-league
type: Opaque
data:
  # Base64 encoded RapidAPI key
  # Use: echo -n "your-rapidapi-key" | base64
  rapidapi_key: N2RhNzg2ZWFhN21zaGE2MDg5YmM1MjI4YjUzOXAxZDI3NTBqc25iMjlmMDMyYzI1OTA=
---
apiVersion: v1
kind: Secret
metadata:
  name: redshift-credentials
  namespace: champions-league
type: Opaque
data:
  # Base64 encoded credentials
  # Use: echo -n "your-username" | base64
  username: YWRtaW4=
  # Use: echo -n "your-password" | base64
  password: Q2hhbXBpb25zTGVhZ3VlMjAyNA==
---
apiVersion: v1
kind: Secret
metadata:
  name: tableau-credentials
  namespace: champions-league
type: Opaque
data:
  # Base64 encoded Tableau credentials
  username: dGFibGVhdV91c2Vy
  password: dGFibGVhdV9wYXNzd29yZA==
  server: dGFibGVhdS1zZXJ2ZXIuY29t
