apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-quality-service
  namespace: champions-league
  labels:
    app: data-quality-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-quality-service
  template:
    metadata:
      labels:
        app: data-quality-service
        version: v1
    spec:
      containers:
      - name: data-quality
        image: champions-league/data-quality:latest
        ports:
        - containerPort: 8080
        env:
        - name: AWS_REGION
          value: "ap-southeast-1"
        - name: S3_BUCKET
          value: "champions-league-data-lake"
        - name: LOG_LEVEL
          value: "INFO"
        - name: GE_STORE_BACKEND
          value: "s3"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: ge-config-volume
          mountPath: /app/great_expectations
      volumes:
      - name: config-volume
        configMap:
          name: data-quality-config
      - name: ge-config-volume
        configMap:
          name: great-expectations-config
      serviceAccountName: data-quality-sa
      nodeSelector:
        kubernetes.io/os: linux
