name: Build and Push CI Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/Dockerfile.ci'
      - 'requirements.txt'
      - 'requirements-dev.txt'

env:
  AWS_REGION: ap-southeast-1
  ECR_REPOSITORY: champions-league/ci-base

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push-ci:
    name: "Build and Push CI Image"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Configure AWS credentials via OIDC"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: "Login to Amazon ECR"
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: "Build, tag, and push image to ECR"
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f docker/Dockerfile.ci .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG